# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ai_rpc_service.object_detect_service.object_detect_pb2 as object__detect__pb2


class RouteGuideStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DetectPicture = channel.unary_unary(
        '/RouteGuide/DetectPicture',
        request_serializer=object__detect__pb2.RequestDetectPicture.SerializeToString,
        response_deserializer=object__detect__pb2.ResponseDetectPicture.FromString,
        )
    self.SayHello = channel.unary_unary(
        '/RouteGuide/SayHello',
        request_serializer=object__detect__pb2.HelloRequest.SerializeToString,
        response_deserializer=object__detect__pb2.HelloResponse.FromString,
        )


class RouteGuideServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DetectPicture(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DetectPicture': grpc.unary_unary_rpc_method_handler(
          servicer.DetectPicture,
          request_deserializer=object__detect__pb2.RequestDetectPicture.FromString,
          response_serializer=object__detect__pb2.ResponseDetectPicture.SerializeToString,
      ),
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=object__detect__pb2.HelloRequest.FromString,
          response_serializer=object__detect__pb2.HelloResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RouteGuide', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
