# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='object_detect.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13object_detect.proto\"[\n\x14RequestDetectPicture\x12\x14\n\x0cpicture_path\x18\x01 \x01(\t\x12\x19\n\x11\x64\x65tect_confidence\x18\x02 \x01(\x02\x12\x12\n\nmodel_name\x18\x03 \x01(\t\";\n\x15ResponseDetectPicture\x12\"\n\x0c\x64\x65tect_param\x18\x01 \x03(\x0b\x32\x0c.DetectParam\"\xcf\x01\n\x0b\x44\x65tectParam\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\x12\x19\n\x11object_confidence\x18\x02 \x01(\x02\x12\"\n\x06lt_box\x18\x04 \x01(\x0b\x32\x12.DetectParam.LtBox\x12\"\n\x06rl_box\x18\x06 \x01(\x0b\x32\x12.DetectParam.RlBox\x1a#\n\x05LtBox\x12\x0c\n\x04lt_x\x18\x01 \x01(\x11\x12\x0c\n\x04lt_y\x18\x02 \x01(\x11\x1a#\n\x05RlBox\x12\x0c\n\x04rl_x\x18\x01 \x01(\x11\x12\x0c\n\x04rl_y\x18\x02 \x01(\x11\" \n\x0cHelloRequest\x12\x10\n\x08greeting\x18\x01 \x01(\t\"\x1e\n\rHelloResponse\x12\r\n\x05reply\x18\x01 \x01(\t2{\n\nRouteGuide\x12@\n\rDetectPicture\x12\x15.RequestDetectPicture\x1a\x16.ResponseDetectPicture\"\x00\x12+\n\x08SayHello\x12\r.HelloRequest\x1a\x0e.HelloResponse\"\x00\x62\x06proto3')
)




_REQUESTDETECTPICTURE = _descriptor.Descriptor(
  name='RequestDetectPicture',
  full_name='RequestDetectPicture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='picture_path', full_name='RequestDetectPicture.picture_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detect_confidence', full_name='RequestDetectPicture.detect_confidence', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_name', full_name='RequestDetectPicture.model_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=114,
)


_RESPONSEDETECTPICTURE = _descriptor.Descriptor(
  name='ResponseDetectPicture',
  full_name='ResponseDetectPicture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detect_param', full_name='ResponseDetectPicture.detect_param', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=175,
)


_DETECTPARAM_LTBOX = _descriptor.Descriptor(
  name='LtBox',
  full_name='DetectParam.LtBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lt_x', full_name='DetectParam.LtBox.lt_x', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lt_y', full_name='DetectParam.LtBox.lt_y', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=348,
)

_DETECTPARAM_RLBOX = _descriptor.Descriptor(
  name='RlBox',
  full_name='DetectParam.RlBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rl_x', full_name='DetectParam.RlBox.rl_x', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rl_y', full_name='DetectParam.RlBox.rl_y', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=385,
)

_DETECTPARAM = _descriptor.Descriptor(
  name='DetectParam',
  full_name='DetectParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_name', full_name='DetectParam.object_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_confidence', full_name='DetectParam.object_confidence', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lt_box', full_name='DetectParam.lt_box', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rl_box', full_name='DetectParam.rl_box', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DETECTPARAM_LTBOX, _DETECTPARAM_RLBOX, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=385,
)


_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='HelloRequest.greeting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=419,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='HelloResponse.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=451,
)

_RESPONSEDETECTPICTURE.fields_by_name['detect_param'].message_type = _DETECTPARAM
_DETECTPARAM_LTBOX.containing_type = _DETECTPARAM
_DETECTPARAM_RLBOX.containing_type = _DETECTPARAM
_DETECTPARAM.fields_by_name['lt_box'].message_type = _DETECTPARAM_LTBOX
_DETECTPARAM.fields_by_name['rl_box'].message_type = _DETECTPARAM_RLBOX
DESCRIPTOR.message_types_by_name['RequestDetectPicture'] = _REQUESTDETECTPICTURE
DESCRIPTOR.message_types_by_name['ResponseDetectPicture'] = _RESPONSEDETECTPICTURE
DESCRIPTOR.message_types_by_name['DetectParam'] = _DETECTPARAM
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestDetectPicture = _reflection.GeneratedProtocolMessageType('RequestDetectPicture', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDETECTPICTURE,
  '__module__' : 'object_detect_pb2'
  # @@protoc_insertion_point(class_scope:RequestDetectPicture)
  })
_sym_db.RegisterMessage(RequestDetectPicture)

ResponseDetectPicture = _reflection.GeneratedProtocolMessageType('ResponseDetectPicture', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDETECTPICTURE,
  '__module__' : 'object_detect_pb2'
  # @@protoc_insertion_point(class_scope:ResponseDetectPicture)
  })
_sym_db.RegisterMessage(ResponseDetectPicture)

DetectParam = _reflection.GeneratedProtocolMessageType('DetectParam', (_message.Message,), {

  'LtBox' : _reflection.GeneratedProtocolMessageType('LtBox', (_message.Message,), {
    'DESCRIPTOR' : _DETECTPARAM_LTBOX,
    '__module__' : 'object_detect_pb2'
    # @@protoc_insertion_point(class_scope:DetectParam.LtBox)
    })
  ,

  'RlBox' : _reflection.GeneratedProtocolMessageType('RlBox', (_message.Message,), {
    'DESCRIPTOR' : _DETECTPARAM_RLBOX,
    '__module__' : 'object_detect_pb2'
    # @@protoc_insertion_point(class_scope:DetectParam.RlBox)
    })
  ,
  'DESCRIPTOR' : _DETECTPARAM,
  '__module__' : 'object_detect_pb2'
  # @@protoc_insertion_point(class_scope:DetectParam)
  })
_sym_db.RegisterMessage(DetectParam)
_sym_db.RegisterMessage(DetectParam.LtBox)
_sym_db.RegisterMessage(DetectParam.RlBox)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'object_detect_pb2'
  # @@protoc_insertion_point(class_scope:HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESPONSE,
  '__module__' : 'object_detect_pb2'
  # @@protoc_insertion_point(class_scope:HelloResponse)
  })
_sym_db.RegisterMessage(HelloResponse)



_ROUTEGUIDE = _descriptor.ServiceDescriptor(
  name='RouteGuide',
  full_name='RouteGuide',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=453,
  serialized_end=576,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectPicture',
    full_name='RouteGuide.DetectPicture',
    index=0,
    containing_service=None,
    input_type=_REQUESTDETECTPICTURE,
    output_type=_RESPONSEDETECTPICTURE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='RouteGuide.SayHello',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTEGUIDE)

DESCRIPTOR.services_by_name['RouteGuide'] = _ROUTEGUIDE

# @@protoc_insertion_point(module_scope)
