# -*- coding: utf-8 -*-
"""
@Time    : 2020-01-08 15:56
@Author  : zhangrui
@FileName: zh_en_dir.py
@Software: PyCharm
模型对应标签名称中英文映射
"""


def zh_en_map(model_name):
    # 顶部摄像盘点数据集
    yike_top_zh_en = {
        "1-1": "货架-货架1",
        "1-2": "货架-货架2",
        "1-3": "货架-货架3",
        "1-4": "货架-货架4",
        "1-5": "货架-货架5",
        "2-1": "椅子-高脚凳",
        "2-2": "椅子",
        "3": "结账机",
        "4-1": "桌子-餐桌",
        "5": "电子屏",
        "6-1": "器具柜-中岛柜",
        "6-2": "器具柜-风幕柜",
        "6-3": "器具柜-中心开放柜",
        "7-1": "冰箱-卧式冰柜",
        "7-2": "冰箱-四门冷藏柜",
        "7-3": "冰箱-单门冷藏柜",
        "7-4": "冰箱-双门冷藏柜",
        "7-5": "冰箱-二门冷藏工作台",
        "8-1": "电子设备-台式电脑",
        "9": "微波炉",
        "10-1": "汤锅-台上式单头多功能蒸煮汤锅",
        "11": "煎饼果子机",
        "12-1": "打印机-标签打印机",
        "12-2": "打印机-热敏打印机",
        "13-1": "电磁炉",
        "14-1": "扫描枪",
        "15-1": "POS机",
        "16-1": "电烤炉",
        "17-1": "面包展示柜-1",
        "17-2": "面包展示柜",
        "18-1": "试吃台",
        "19-1": "餐具-1",
        "19-2": "餐具-2",
        "20-1": "茶桶-不锈钢电热奶茶桶",
        "21-1": "榨汁机-1",
        "21-2": "榨汁机-2",
        "22-1": "冰淇淋机-三头桌上型冰激凌机",
        "23-1": "开水机-步进式开水机",
        "23-2": "开水机-蒸汽开水机",
        "24-1": "咖啡机-1",
        "25": "钱箱",
        "26-1": "电子秤"
    }
    # 手持盘点数据集
    yike_handle_zh_en = {
        "1-1": "货架-货架1",
        "1-2": "货架-货架2",
        "1-3": "货架-货架3",
        "1-4": "货架-货架4",
        "1-5": "货架-货架5",
        "2-1": "椅子-高脚凳",
        "2-2": "椅子",
        "3": "结账机",
        "4-1": "桌子-餐桌",
        "5": "电子屏",
        "6-1": "器具柜-中岛柜",
        "6-2": "器具柜-风幕柜",
        "6-3": "器具柜-中心开放柜",
        "7-1": "冰箱-卧式冰柜",
        "7-2": "冰箱-四门冷藏柜",
        "7-3": "冰箱-单门冷藏柜",
        "7-4": "冰箱-双门冷藏柜",
        "7-5": "冰箱-二门冷藏工作台",
        "8-1": "电子设备-台式电脑",
        "9": "微波炉",
        "10-1": "汤锅-台上式单头多功能蒸煮汤锅",
        "11": "煎饼果子机",
        "12-1": "打印机-标签打印机",
        "12-2": "打印机-热敏打印机",
        "13-1": "电磁炉",
        "14-1": "扫描枪",
        "15-1": "POS机",
        "16-1": "电烤炉",
        "17-1": "面包展示柜-1",
        "17-2": "面包展示柜",
        "18-1": "试吃台",
        "19-1": "餐具-1",
        "19-2": "餐具-2",
        "20-1": "茶桶-不锈钢电热奶茶桶",
        "21-1": "榨汁机-1",
        "21-2": "榨汁机-2",
        "22-1": "冰淇淋机-三头桌上型冰激凌机",
        "23-1": "开水机-步进式开水机",
        "23-2": "开水机-蒸汽开水机",
        "24-1": "咖啡机-1",
        "25": "钱箱",
        "26-1": "电子秤"
    }
    # coco数据集
    common_zh_en = {
        "person": "人",
        "bicycle": "自行车",
        "car": "汽车",
        "motorbike": "摩托车",
        "aeroplane": "飞机",
        "bus": "公交车",
        "train": "火车",
        "truck": "卡车",
        "boat": "船",
        "traffic light": "红绿灯",
        "fire hydrant ": "消防栓",
        "stop sign": "停止标志",
        "parking meter": "停车收费表",
        "bench": "板凳",
        "bird": "鸟",
        "cat": "猫",
        "dog": "狗",
        "horse": "马",
        "sheep": "羊",
        "cow": "牛",
        "elephant": "象",
        "bear": "熊",
        "zebra": "斑马",
        "giraffe": "长颈鹿",
        "backpack": "背包",
        "umbrella": "雨伞",
        "handbag": "手提包",
        "tie": "领带",
        "suitcase": "手提箱",
        "frisbee": "飞盘",
        "skis": "滑雪板",
        "snowboard": "单板滑雪",
        "sports ball": "运动球",
        "kite": "风筝",
        "baseball bat": "棒球棒",
        "baseball glove": "棒球手套",
        "skateboard": "滑板",
        "surfboard": "冲浪板",
        "tennis racket": "网球拍",
        "bottle": "瓶子",
        "wine glass": "红酒杯",
        "cup": "杯子",
        "fork": "叉子",
        "knife": "刀",
        "spoon": "勺",
        "bowl": "碗",
        "banana": "香蕉",
        "apple": "苹果",
        "sandwich": "三明治",
        "orange": "橙子",
        "broccoli": "西兰花",
        "carrot": "胡萝卜",
        "hot dog": "热狗",
        "pizza": "比萨",
        "donut": "甜甜圈",
        "cake": "蛋糕",
        "chair": "椅子",
        "sofa": "沙发",
        "pottedplant": "盆栽植物",
        "bed": "床",
        "diningtable": "餐桌",
        "toilet": "厕所",
        "tvmonitor": "电视监视器",
        "laptop": "笔记本电脑",
        "mouse": "鼠标",
        "remote": "远程",
        "keyboard": "键盘",
        "cell phone": "手机",
        "microwave": "微波炉",
        "oven": "烤箱",
        "toaster": "烤面包机",
        "sink": "水槽",
        "refrigerator": "冰箱",
        "book": "书",
        "clock": "时钟",
        "vase": "花瓶",
        "scissors": "剪刀",
        "teddy bear": "泰迪熊",
        "hair drier": "吹风机",
        "toothbrush": "牙刷",
    }
    openimage_zh_en = {
        "Blender": "搅拌机",
        "Coffeemaker": "咖啡机",
        "Oven": "烤箱",
        "Microwave_oven": "微波炉",
        "Grinder": "磨床",
        "Chair": "椅子",
        "Refrigerator": "冰箱",
        "Cake_stand": "蛋糕展示柜",
        "Wardrobe": "衣柜",
        "Printer": "打印机",
        "Laptop": "笔记本电脑",
        "Tablet_computer": "平板电脑",
        "Camera": "相机",
        "Mobile_phone": "移动电话",
        "Table": "桌子",
        "Tableware": "餐具",
        "Coffee_table": "咖啡桌",
        "Wok": "炒锅",
        "Dishwasher": "洗碗机",
        "Cupboard": "橱柜",
        "Spoon": "勺",
        "Fork": "叉子",
        "Hot_dog": "热狗"
    }
    if model_name == "yike_top_model":
        return yike_top_zh_en
    elif model_name == "yike_handle_model":
        return yike_handle_zh_en
    elif model_name == "coco_model":
        return common_zh_en
    elif model_name == "open_model":
        return openimage_zh_en
