# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_count.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='object_count.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12object_count.proto\"W\n\x12ObjectCountRequest\x12\x12\n\nvideo_path\x18\x01 \x01(\t\x12\x19\n\x11\x64\x65tect_confidence\x18\x02 \x01(\x02\x12\x12\n\nmodel_name\x18\x03 \x01(\t\"9\n\x13ObjectCountResponse\x12\"\n\x0cobject_param\x18\x01 \x03(\x0b\x32\x0c.ObjectParam\"7\n\x0bObjectParam\x12\x14\n\x0cobject_label\x18\x01 \x01(\t\x12\x12\n\nobject_num\x18\x02 \x01(\x11\x32\x90\x01\n\x0bObjectCount\x12?\n\x10TrackObjectCount\x12\x13.ObjectCountRequest\x1a\x14.ObjectCountResponse\"\x00\x12@\n\x11StitchObjectCount\x12\x13.ObjectCountRequest\x1a\x14.ObjectCountResponse\"\x00\x62\x06proto3')
)




_OBJECTCOUNTREQUEST = _descriptor.Descriptor(
  name='ObjectCountRequest',
  full_name='ObjectCountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_path', full_name='ObjectCountRequest.video_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detect_confidence', full_name='ObjectCountRequest.detect_confidence', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_name', full_name='ObjectCountRequest.model_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=109,
)


_OBJECTCOUNTRESPONSE = _descriptor.Descriptor(
  name='ObjectCountResponse',
  full_name='ObjectCountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_param', full_name='ObjectCountResponse.object_param', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=168,
)


_OBJECTPARAM = _descriptor.Descriptor(
  name='ObjectParam',
  full_name='ObjectParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_label', full_name='ObjectParam.object_label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_num', full_name='ObjectParam.object_num', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=225,
)

_OBJECTCOUNTRESPONSE.fields_by_name['object_param'].message_type = _OBJECTPARAM
DESCRIPTOR.message_types_by_name['ObjectCountRequest'] = _OBJECTCOUNTREQUEST
DESCRIPTOR.message_types_by_name['ObjectCountResponse'] = _OBJECTCOUNTRESPONSE
DESCRIPTOR.message_types_by_name['ObjectParam'] = _OBJECTPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectCountRequest = _reflection.GeneratedProtocolMessageType('ObjectCountRequest', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTCOUNTREQUEST,
  '__module__' : 'object_count_pb2'
  # @@protoc_insertion_point(class_scope:ObjectCountRequest)
  })
_sym_db.RegisterMessage(ObjectCountRequest)

ObjectCountResponse = _reflection.GeneratedProtocolMessageType('ObjectCountResponse', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTCOUNTRESPONSE,
  '__module__' : 'object_count_pb2'
  # @@protoc_insertion_point(class_scope:ObjectCountResponse)
  })
_sym_db.RegisterMessage(ObjectCountResponse)

ObjectParam = _reflection.GeneratedProtocolMessageType('ObjectParam', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTPARAM,
  '__module__' : 'object_count_pb2'
  # @@protoc_insertion_point(class_scope:ObjectParam)
  })
_sym_db.RegisterMessage(ObjectParam)



_OBJECTCOUNT = _descriptor.ServiceDescriptor(
  name='ObjectCount',
  full_name='ObjectCount',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=228,
  serialized_end=372,
  methods=[
  _descriptor.MethodDescriptor(
    name='TrackObjectCount',
    full_name='ObjectCount.TrackObjectCount',
    index=0,
    containing_service=None,
    input_type=_OBJECTCOUNTREQUEST,
    output_type=_OBJECTCOUNTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StitchObjectCount',
    full_name='ObjectCount.StitchObjectCount',
    index=1,
    containing_service=None,
    input_type=_OBJECTCOUNTREQUEST,
    output_type=_OBJECTCOUNTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBJECTCOUNT)

DESCRIPTOR.services_by_name['ObjectCount'] = _OBJECTCOUNT

# @@protoc_insertion_point(module_scope)
