# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ai_rpc_service.object_count_service.object_count_pb2 as object__count__pb2


class ObjectCountStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TrackObjectCount = channel.unary_unary(
        '/ObjectCount/TrackObjectCount',
        request_serializer=object__count__pb2.ObjectCountRequest.SerializeToString,
        response_deserializer=object__count__pb2.ObjectCountResponse.FromString,
        )
    self.StitchObjectCount = channel.unary_unary(
        '/ObjectCount/StitchObjectCount',
        request_serializer=object__count__pb2.ObjectCountRequest.SerializeToString,
        response_deserializer=object__count__pb2.ObjectCountResponse.FromString,
        )


class ObjectCountServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TrackObjectCount(self, request, context):
    """视频跟踪盘点
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StitchObjectCount(self, request, context):
    """视频图像拼接盘点
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ObjectCountServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TrackObjectCount': grpc.unary_unary_rpc_method_handler(
          servicer.TrackObjectCount,
          request_deserializer=object__count__pb2.ObjectCountRequest.FromString,
          response_serializer=object__count__pb2.ObjectCountResponse.SerializeToString,
      ),
      'StitchObjectCount': grpc.unary_unary_rpc_method_handler(
          servicer.StitchObjectCount,
          request_deserializer=object__count__pb2.ObjectCountRequest.FromString,
          response_serializer=object__count__pb2.ObjectCountResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ObjectCount', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
